// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTGrRuuxPEboKd_XxvrLbrZSTZc1cQ1kA',
    appId: '1:458251310978:web:e0e41748760de5c2aba19b',
    messagingSenderId: '458251310978',
    projectId: 'fir-oscar-71fe3',
    authDomain: 'fir-oscar-71fe3.firebaseapp.com',
    storageBucket: 'fir-oscar-71fe3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfq_QNmEcL_ZEVqrM1xJABLi_56cEVl4s',
    appId: '1:458251310978:android:ccdcf94af96ca1daaba19b',
    messagingSenderId: '458251310978',
    projectId: 'fir-oscar-71fe3',
    storageBucket: 'fir-oscar-71fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSf2UxzGg12qEA9eJ7-9hxdNfB1OMgi4',
    appId: '1:458251310978:ios:eb2d3aa8167322f4aba19b',
    messagingSenderId: '458251310978',
    projectId: 'fir-oscar-71fe3',
    storageBucket: 'fir-oscar-71fe3.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSf2UxzGg12qEA9eJ7-9hxdNfB1OMgi4',
    appId: '1:458251310978:ios:34e05ca6f3bfe28baba19b',
    messagingSenderId: '458251310978',
    projectId: 'fir-oscar-71fe3',
    storageBucket: 'fir-oscar-71fe3.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324.RunnerTests',
  );
}
